### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by elodani10** [Teaching-projects/SZE-FordProg-2020-Calculator#1]

**Comment by hegyhati** [comment]
Jonak nez ki, csak az `ANS` es `ans` kozotti kulonbseget lehet nem teljesen ertem. A peldadban amikor hasznalod, akkor az `ans` az 10. Ha jol ertem akkor a vegeredmenynek utana 600-nak kellene lennie. vagy amikor `ANS`-ot hasznalunk, akkor az abban levo `ans` az a 2-vel ezelotti eredmeny? Nekem ez bugnak tunik, de javits ki, ha tevedek.

**Comment by elodani10** [comment]
Azért van megkülönböztetve, hogyha egy teljes Expressiont helyettesítenénk, akkor az ANS a megfelelő, ha egy Expressionön belül helyettesítenénk egy számot, akkor pedig ans.
Példában:
(ANS)x(ans x ans)
Az ANS és az ans értéke ugyanannyi, tehát (10)x(10 x 10)=1000

**Comment by hegyhati** [comment]
Ennek igy nem sok ertelmet latom. Marmint ennyi erovel lehetne egy `expression -> ans` szabaly is, es akkor nem kell kulon szorakozni azzal, hogy ketfele ans/ANS van.  Lehet en ertelmezem rosszul, de az ANS-nak nem az lenne a lenyege,hogy magat az elozo expression-t helyettesiti be?

tehat:
```
> 2
2
> ans
2
> ANS
2
> ans + 3
5
> ans
5
> ans * 2
10
> ANS                   <---- vagyis mintha beirnam, hogy ans * 2
20
> ANS 
40
> ans
40
> ANS                
40 
```

**Comment by elodani10** [comment]
Nem, csak az előtte kapott eredményt.
Azért lett külön ans és ANS, mert a beírt szám (Ident) lehet ans, így ha az Expression-ön belül a kis ans lenne használva, akkor a kezdő szimbólum lehetne a záró is.

2
2.0
Next calculation
ans
2.0
Next calculation
ANS
2.0
Next calculation
ans+3
5.0
Next calculation
ans
5.0
Next calculation
ans*2
10.0
Next calculation
ANS
10.0
Next calculation
ANS
10.0
Next calculation
ans
10.0

**Comment by hegyhati** [comment]
Az indoklast tovabbra sem ertem. Mi ez a kezdoszimbolum meg zaro? PRbaltam most a nyelvtanodbol mefejteni a dolgot, de elegge osszevissza csuszkal az indentalas (valoszinuleg vegyes tab es space hasznalat miatt),  szoval nem lettem kozelebb.

**Comment by elodani10** [comment]
Ident felépítése:
 Ident<out double n>    (.n=0.0;.)

 =
 ident (. n = Double.parseDouble(t.val);.)
 | ans (. n = calculator.getAns();.)
  .
 Ez alapján egy ans kifejezés azonosíthat egy Identet.

Expression<out double ret> (.double n1; double n2; String s=null;ret=0.0;.)

=
Ident<out n1> (.ret=n1;.)
{
 Operation<out s>
 Ident<out n2> (. if(s==null) ret=n1+n2;
                   else if(s.equals("+")) ret=ret+n2;
                else if(s.equals("-")) ret=ret-n2;
               else if(s.equals("/")) ret=ret/n2;
               else if(s.equals("*")) ret=ret*n2;
                else ret=ret+n2;.)
                }
                |
                ANS (.ret=calculator.getAns();.)
                .

Ha itt kis ans szerepel, akkor az Ident (ami lehet ans) | ans lenne, ami nem helyes.

**Comment by hegyhati** [comment]
Ah, igy ertem. 

Gyors megjegyzes a backtick hasznos dolog kodok beemelesehez, a 3 backtick meg tobbsoros kod beemelesehez ;-) 

Viszont igy az ANS-nak az eg egy adta vilagon semmi ertelme nincs, ki lehetne torolni szabalyostul ugy ahogy van, mert ha jol ertem, `Expression` kicserelheto egyetlen `Ident`-re, ami kicserelheto `ans`-ra. Szoval igazabol semmilyen funkcionalitast nem ad hozza. De ha ebben tevedek, javits ki. 

Mindenesetre az a funkcio,amire en gondoltam, az jopofa lenne egyfajta rekurzio, olyasmi, mint mikor a szamologepen az =-t nyomogatja az ember. 

Most igy kicsit a 4-es fele hajlok, de nagyon szivesen adnek otost, es ennek a megvalositasa nem is lnene nagy tortenet (csak el kellene menteni a teljes elozo parzolt kifejezest, es mielott a bemenetet parzolnad, mindenhol az ANS-ot (vagy lehet mas is a neve) lecserelni arra, ami az elozo volt. Arra kell csak vigyazni, hogy a "mi volt az elozo" azt mar ezutan a csere utan kell update-elni,kulonben szepen vegtelen ciklusba lehet keveredni :-D )

**Comment by elodani10** [comment]
Igen, jogos felvetés az ANS-al kapcsolatban.
Sajnos nem sok időm van mostanában, így megelégednék a 4-essel.
( A feladatot elkészíteni meglepően élvezetes volt, jó, hogy nem egy szokásos beadandó, hanem valami új "világ")

**Comment by hegyhati** [comment]
Rendben, akkor legyen igy, orulok, hogy tetszett. Ha meg valamelyik kesobbi vizsgaalkalom elott megis megcsinalnad, akkor nyiss egy uj issue-t. Minden jot!
